namespace BaseDefense.State
{
	public enum StateTriggers
	{
		NONE,
		LOADING_COMPLETED,
		PLAY_GAME_REQUEST,
		REPLAY_GAME_REQUEST,
		GO_TO_BATTLE_REQUEST,
		GO_TO_UPGRADE_REQUEST,
		RETURN_UPGRADE_IDLE_STATE,
		TURRET_CONTROL_REQUEST,

	}

}